<a href="https://colab.research.google.com/github/kwansawanth/python_dataviz2023/blob/main/Final2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Final Exam

รายชื่อสมาชิกภายในกลุ่ม

1. นางสาวฐาปนี ฟุ้งขจร  633020670-2
2. นางสาวขวัญสวรรค์ ทองประเสริฐ  643020498-9
3. นายธนบดี ภูชมศรี  643020502-4
4. นางสาวนริศรา โยธาจันทร์  643020504-0
5. นายปิยพัทธ์ ปานะถึก  643020507-4
6. นางสาวกิติลักษณ์ ลาดโฮม  643021260-7

# เชื่อม Drive เพื่อดึงข้อมูลมาใช้งาน

In [ ]:
from google.colab import drive # เชื่อมบัญชีกับ google drive
drive.mount('/content/drive') # เช็คว่าเชื่อมติดหรือไม่
import pandas as pd

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# เปิด File

In [ ]:
Pos_tran1 = pd.read_csv('/content/drive/MyDrive/final2023/Final2023_DataViz/POS_transactions_20171207-20171219.csv')
Pos_tran2 = pd.read_csv('/content/drive/MyDrive/final2023/Final2023_DataViz/POS_transactions_20190213-20190226.csv')
Pos_tran3= pd.read_csv('/content/drive/MyDrive/final2023/Final2023_DataViz/POS_transactions_20190328-20190410.csv')

In [ ]:
Pos_opr1 = pd.read_csv('/content/drive/MyDrive/final2023/Final2023_DataViz/POS_operator_logs_20171207-20171219.csv')
Pos_opr2 = pd.read_csv('/content/drive/MyDrive/final2023/Final2023_DataViz/POS_operator_logs_20190213-20190226.csv')
Pos_opr3 = pd.read_csv('/content/drive/MyDrive/final2023/Final2023_DataViz/POS_operator_logs_20190328-20190410.csv')

In [ ]:
Pos_tran1

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,171207106022464,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,171207106022465,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,171207106022466,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,171207106022467,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,171207106022468,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...
66858,1,1712191060847,2017-12-19T11:48:35,2017-12-19T11:49:28,606,53,19,6,True,False,36.27
66859,1,1712191060848,2017-12-19T11:49:47,2017-12-19T11:50:24,606,37,15,10,True,False,43.16
66860,1,1712191060849,2017-12-19T11:50:39,2017-12-19T11:51:22,606,43,14,11,False,True,39.58
66861,1,1712191060851,2017-12-19T11:51:36,2017-12-19T11:52:28,606,52,9,9,False,True,113.96
66862,1,1712191060853,2017-12-19T11:52:37,2017-12-19T11:53:39,606,62,15,25,True,False,97.58

# ตรวจสอบค่า NULL

In [ ]:
Pos_tran1.isnull()

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
66858,False,False,False,False,False,False,False,False,False,False,False
66859,False,False,False,False,False,False,False,False,False,False,False
66860,False,False,False,False,False,False,False,False,False,False,False
66861,False,False,False,False,False,False,False,False,False,False,False
66862,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
Pos_opr1.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [ ]:
Pos_opr2.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [ ]:
Pos_opr3.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [ ]:
Pos_opr1.head()

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn

In [ ]:
Pos_opr2.head()

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,19,1902131060192,2019-02-13T05:37:55,269,OperatorSignOn
1,8,18,1902131060182,2019-02-13T05:37:55,268,OperatorSignOn
2,8,17,1902131060172,2019-02-13T05:38:43,267,OperatorSignOn
3,1,4,190213106042,2019-02-13T07:01:26,332,OperatorSignOn
4,1,7,190213106072,2019-02-13T07:01:57,10,OperatorSignOn

In [ ]:
Pos_opr3.head()

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,19,1903281060192,2019-03-28T06:08:13,269,OperatorSignOn
1,8,18,1903281060182,2019-03-28T06:09:13,268,OperatorSignOn
2,8,17,1903281060172,2019-03-28T06:08:33,267,OperatorSignOn
3,1,4,190328106042,2019-03-28T07:04:45,104,OperatorSignOn
4,1,6,190328106062,2019-03-28T07:18:38,125,OperatorSignOn

In [ ]:
import pandas as pd

In [ ]:
operator = pd.concat([Pos_opr1, Pos_opr2, Pos_opr3])
operator

,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
...,...,...,...,...,...,...
4173,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff
4174,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff
4175,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn
4176,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff
4177,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff

In [ ]:
operator.isnull().any()

WorkstationGroupID    False
WorkstationID         False
TranID                False
BeginDateTime         False
OperatorID            False
Items                 False
dtype: bool

In [ ]:
transaction = pd.concat([Pos_tran1, Pos_tran2, Pos_tran3])
transaction

,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,1,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,1,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,1,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,1,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...
49335,1,1.904101e+14,2019-04-10T14:05:20,2019-04-10T14:06:14,606,54,25,7,True,False,12.14
49336,1,1.904101e+14,2019-04-10T14:06:39,2019-04-10T14:07:35,606,56,16,24,False,True,99.90
49337,1,1.904101e+14,2019-04-10T14:07:51,2019-04-10T14:09:27,606,96,19,47,True,False,106.99
49338,1,1.904101e+14,2019-04-10T14:09:46,2019-04-10T14:10:03,606,17,26,4,True,False,30.88
49339,1,1.904101e+14,2019-04-10T14:10:29,2019-04-10T14:10:55,606,26,28,4,True,False,54.33

In [ ]:
transaction['TranID']

0        1.712071e+14
1        1.712071e+14
2        1.712071e+14
3        1.712071e+14
4        1.712071e+14
             ...
49335    1.904101e+14
49336    1.904101e+14
49337    1.904101e+14
49338    1.904101e+14
49339    1.904101e+14
Name: TranID, Length: 163269, dtype: float64

In [ ]:
transaction.isnull().any()

WorkstationGroupID    False
TranID                False
BeginDateTime         False
EndDateTime           False
OperatorID            False
TranTime              False
BreakTime             False
ArtNum                False
TNcash                False
TNcard                False
Amount                False
dtype: bool

In [ ]:
bool_series1 = transaction.duplicated(subset='TranID')
# passing NOT of bool series to see unique values only (ดูเฉพาะค่าที่ไม่ซ้ำ)
tr= transaction[~bool_series1]
# displaying data (ดูผลลัพธ์)
tr1 = tr.reset_index() # .reset_index() เพื่อจัดเรียงให้เป็นระเบียบ
tr1

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,0,1,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,False,112.71
1,1,1,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,False,54.76
2,2,1,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,False,14.77
3,3,1,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,False,37.88
4,4,1,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,False,115.34
...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,1,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,True,False,24.93
126955,48552,1,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,True,False,51.71
126956,48553,1,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,True,False,41.95
126957,48554,1,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,False,True,47.96
126958,48555,1,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,True,False,17.45

In [ ]:
bool_series = operator.duplicated(subset='TranID')
# passing NOT of bool series to see unique values only (ดูเฉพาะค่าที่ไม่ซ้ำ)
op = operator[~bool_series]
# displaying data (ดูผลลัพธ์)
op1 = op.reset_index() # .reset_index() เพื่อจัดเรียงให้เป็นระเบียบ
op1

,index,WorkstationGroupID,WorkstationID,TranID,BeginDateTime,OperatorID,Items
0,0,8,16,1712071060162,2017-12-07T06:04:01,266,OperatorSignOn
1,1,8,15,1712071060152,2017-12-07T06:04:15,265,OperatorSignOn
2,2,8,14,1712071060142,2017-12-07T06:05:36,264,OperatorSignOn
3,3,8,18,1712071060182,2017-12-07T06:05:41,268,OperatorSignOn
4,4,8,17,1712071060172,2017-12-07T06:05:56,267,OperatorSignOn
...,...,...,...,...,...,...,...
14069,4173,1,3,19041010603798,2019-04-10T21:53:58,104,OperatorSignOff
14070,4174,1,4,190410106041042,2019-04-10T21:54:30,304,OperatorSignOff
14071,4175,1,4,190410106041044,2019-04-10T21:55:05,104,OperatorSignOn
14072,4176,1,5,19041010605515,2019-04-10T22:00:25,136,OperatorSignOff
14073,4177,1,4,190410106041061,2019-04-10T22:10:57,104,OperatorSignOff

In [ ]:
import datetime #import datetime เพื่อใช้

In [ ]:
tr1['BeginDateTime'] #check value ใน BeginDateTime

0         2017-12-07T14-23-23
1         2017-12-07T14-25-09
2         2017-12-07T14-27-28
3         2017-12-07T14-28-04
4         2017-12-07T14-29-40
                 ...
126954    2019-04-02T11-08-22
126955    2019-04-02T11-09-30
126956    2019-04-02T11-10-21
126957    2019-04-02T11-11-13
126958    2019-04-02T11-11-54
Name: BeginDateTime, Length: 126959, dtype: object

#นำไปทำDashboard

In [ ]:
import datetime as dt

In [ ]:
tr1

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,0,1,1.712071e+14,2017-12-07T14-23-23,2017-12-07T14:24:36,101,73,33,23,True,Cash,112.71
1,1,1,1.712071e+14,2017-12-07T14-25-09,2017-12-07T14:27:00,101,111,28,29,True,Cash,54.76
2,2,1,1.712071e+14,2017-12-07T14-27-28,2017-12-07T14:27:48,101,20,16,3,True,Cash,14.77
3,3,1,1.712071e+14,2017-12-07T14-28-04,2017-12-07T14:28:29,101,25,71,12,True,Cash,37.88
4,4,1,1.712071e+14,2017-12-07T14-29-40,2017-12-07T14:30:32,101,52,31,7,True,Cash,115.34
...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,1,1.904021e+11,2019-04-02T11-08-22,2019-04-02T11:09:14,603,52,16,8,True,Cash,24.93
126955,48552,1,1.904021e+11,2019-04-02T11-09-30,2019-04-02T11:10:04,603,34,17,17,True,Cash,51.71
126956,48553,1,1.904021e+11,2019-04-02T11-10-21,2019-04-02T11:11:03,603,42,10,19,True,Cash,41.95
126957,48554,1,1.904021e+11,2019-04-02T11-11-13,2019-04-02T11:11:42,603,29,12,9,False,Card,47.96
126958,48555,1,1.904021e+11,2019-04-02T11-11-54,2019-04-02T11:12:16,603,22,7,6,True,Cash,17.45

In [ ]:
tr1.loc[tr1['TNcard']== 'Service', "TNcard"] = 'Cash'
tr1

In [ ]:
tr1['Date'] = tr['BeginDateTime'].dt.date #split date and time

In [ ]:
tr1.loc[tr1['WorkstationGroupID']== 1, "WorkstationGroupID"] = 'Service' #เปลี่ยน จากID 1 service
tr1

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Date,WorkstationGroupID\t
0,0,Service,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,Cash,112.71,2017-12-07,Service
1,1,Service,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,Cash,54.76,2017-12-07,Service
2,2,Service,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,Cash,14.77,2017-12-07,Service
3,3,Service,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,Cash,37.88,2017-12-07,Service
4,4,Service,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,Cash,115.34,2017-12-07,Service
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,Service,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,True,Cash,24.93,2019-04-02,Service
126955,48552,Service,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,True,Cash,51.71,2019-04-02,Service
126956,48553,Service,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,True,Cash,41.95,2019-04-02,Service
126957,48554,Service,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,False,Cash,47.96,2019-04-02,Service
126958,48555,Service,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,True,Cash,17.45,2019-04-02,Service

In [ ]:
tr1.loc[tr1['WorkstationGroupID'] == 8, "WorkstationGroupID"] = 'Self-Service' #เปลี่ยน จากID 8 Self-service
tr1[tr1['WorkstationGroupID'] == 'Self-Service']

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Date,WorkstationGroupID\t
0,0,Service,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,Cash,112.71,2017-12-07,Service
1,1,Service,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,Cash,54.76,2017-12-07,Service
2,2,Service,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,Cash,14.77,2017-12-07,Service
3,3,Service,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,Cash,37.88,2017-12-07,Service
4,4,Service,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,Cash,115.34,2017-12-07,Service
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,Service,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,True,Cash,24.93,2019-04-02,Service
126955,48552,Service,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,True,Cash,51.71,2019-04-02,Service
126956,48553,Service,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,True,Cash,41.95,2019-04-02,Service
126957,48554,Service,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,False,Cash,47.96,2019-04-02,Service
126958,48555,Service,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,True,Cash,17.45,2019-04-02,Service

In [244]:
tr1

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Date,WorkstationGroupID\t
0,0,Service,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,True,Cash,112.71,2017-12-07,Service
1,1,Service,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,True,Cash,54.76,2017-12-07,Service
2,2,Service,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,True,Cash,14.77,2017-12-07,Service
3,3,Service,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,True,Cash,37.88,2017-12-07,Service
4,4,Service,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,True,Cash,115.34,2017-12-07,Service
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,Service,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,True,Cash,24.93,2019-04-02,Service
126955,48552,Service,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,True,Cash,51.71,2019-04-02,Service
126956,48553,Service,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,True,Cash,41.95,2019-04-02,Service
126957,48554,Service,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,Card,Cash,47.96,2019-04-02,Service
126958,48555,Service,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,True,Cash,17.45,2019-04-02,Service

In [249]:
tr1[tr1['WorkstationGroupID'] == 'Self-Service'] #check self-service ว่าเปลี่ยนแล้ว

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Date,WorkstationGroupID\t
45410,45410,Self-Service,1.712071e+12,2017-12-07T07:00:41,2017-12-07T07:01:33,264,52,388,2,Card,Cash,23.98,2017-12-07,NaN
45411,45411,Self-Service,1.712071e+12,2017-12-07T07:08:01,2017-12-07T07:09:58,264,117,93,9,Card,Cash,73.60,2017-12-07,NaN
45412,45412,Self-Service,1.712071e+12,2017-12-07T07:11:31,2017-12-07T07:15:09,264,218,44,7,Card,Cash,21.45,2017-12-07,NaN
45413,45413,Self-Service,1.712071e+13,2017-12-07T07:15:53,2017-12-07T07:17:00,264,67,84,7,Card,Cash,64.82,2017-12-07,NaN
45414,45414,Self-Service,1.712071e+13,2017-12-07T07:18:24,2017-12-07T07:18:40,264,16,95,1,Card,Cash,1.09,2017-12-07,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98404,31628,Self-Service,1.902261e+14,2019-02-26T21:01:45,2019-02-26T21:03:09,269,84,320,14,True,False,23.31,2019-02-26,NaN
98405,31629,Self-Service,1.902261e+14,2019-02-26T21:08:29,2019-02-26T21:09:41,269,72,289,5,True,False,38.76,2019-02-26,NaN
126884,31889,Self-Service,1.903311e+14,2019-03-31T13:04:30,2019-03-31T13:06:48,267,138,709,6,True,False,21.97,2019-03-31,NaN
126885,32100,Self-Service,1.904011e+14,2019-04-01T11:36:32,2019-04-01T11:41:08,267,276,198,36,True,False,134.30,2019-04-01,NaN
126886,32355,Self-Service,1.904021e+14,2019-04-02T11:15:35,2019-04-02T11:16:47,267,72,241,6,True,False,31.74,2019-04-02,NaN

In [256]:
tr1.loc[tr1['TNcash']== True, "TNcash"] = 'Cash'. #เปลี่ยน True เป็น cash
tr1

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Date,WorkstationGroupID\t
0,0,Service,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,Cash,Cash,112.71,2017-12-07,Service
1,1,Service,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,Cash,Cash,54.76,2017-12-07,Service
2,2,Service,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,Cash,Cash,14.77,2017-12-07,Service
3,3,Service,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,Cash,Cash,37.88,2017-12-07,Service
4,4,Service,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,Cash,Cash,115.34,2017-12-07,Service
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,Service,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,Cash,Cash,24.93,2019-04-02,Service
126955,48552,Service,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,Cash,Cash,51.71,2019-04-02,Service
126956,48553,Service,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,Cash,Cash,41.95,2019-04-02,Service
126957,48554,Service,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,Card,Cash,47.96,2019-04-02,Service
126958,48555,Service,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,Cash,Cash,17.45,2019-04-02,Service

In [257]:
tr1

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount,Date,WorkstationGroupID\t
0,0,Service,1.712071e+14,2017-12-07T14:23:23,2017-12-07T14:24:36,101,73,33,23,Cash,Cash,112.71,2017-12-07,Service
1,1,Service,1.712071e+14,2017-12-07T14:25:09,2017-12-07T14:27:00,101,111,28,29,Cash,Cash,54.76,2017-12-07,Service
2,2,Service,1.712071e+14,2017-12-07T14:27:28,2017-12-07T14:27:48,101,20,16,3,Cash,Cash,14.77,2017-12-07,Service
3,3,Service,1.712071e+14,2017-12-07T14:28:04,2017-12-07T14:28:29,101,25,71,12,Cash,Cash,37.88,2017-12-07,Service
4,4,Service,1.712071e+14,2017-12-07T14:29:40,2017-12-07T14:30:32,101,52,31,7,Cash,Cash,115.34,2017-12-07,Service
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,Service,1.904021e+11,2019-04-02T11:08:22,2019-04-02T11:09:14,603,52,16,8,Cash,Cash,24.93,2019-04-02,Service
126955,48552,Service,1.904021e+11,2019-04-02T11:09:30,2019-04-02T11:10:04,603,34,17,17,Cash,Cash,51.71,2019-04-02,Service
126956,48553,Service,1.904021e+11,2019-04-02T11:10:21,2019-04-02T11:11:03,603,42,10,19,Cash,Cash,41.95,2019-04-02,Service
126957,48554,Service,1.904021e+11,2019-04-02T11:11:13,2019-04-02T11:11:42,603,29,12,9,Card,Cash,47.96,2019-04-02,Service
126958,48555,Service,1.904021e+11,2019-04-02T11:11:54,2019-04-02T11:12:16,603,22,7,6,Cash,Cash,17.45,2019-04-02,Service

In [258]:
tr1.to_csv('tran_full.csv', index=False)  #เอาtr1เข้า

#Testcode

In [ ]:
for_test1 = tr1[['TranID','Date','TNcash','TNcard','Amount']]
for_test1.to_csv('grouby.csv', index=False)

KeyError: ignored

In [ ]:
for_test1.to_csv('grouby', index=False)

In [ ]:
for_test1 = tr1[['TranID','Date','TNcash','TNcard','Amount']]
for_test1.groupby('TNcash').count().reset_index()

KeyError: ignored

In [ ]:
for_test1.groupby('TNcard').count().reset_index()

In [ ]:

group_TNcard = tr1[['TNcard','Amount']].groupby('TNcard').count().reset_index()
group_TNcard

In [ ]:
group_TNcash = tr1[['TNcash','Amount']].groupby('TNcash').count().reset_index()
group_TNcash

In [ ]:
group_TNcash.to_csv('Cash1.csv', index=False)

In [ ]:
p_1=pd.concat([group_TNcash,group_TNcard])
p_1

In [ ]:
group_TNcash[['TNcard','Amount_card']] = group_TNcard
group_TNcard

In [ ]:
tr1[['TNcard']]

In [ ]:
import numpy as np

In [ ]:
tr1['TNcard'] = tr1['TNcard'].replace({True: 'Card'})

In [ ]:
data = tr1['TNcard'].replace(to_replace=['True'],
    value='Card',
    inplace=True)

In [ ]:
tr1['TNcard'].replace(to_replace=['False'],
    value='Nocard',
    inplace=True)

In [ ]:
tr1["TNcard"].replace(["False"], "Nocard", inplace=True)

In [ ]:
tr1.loc[tr1['TNcash']== 'True', "TNcash"] = "Cash"
tr1

,index,WorkstationGroupID,TranID,BeginDateTime,EndDateTime,OperatorID,TranTime,BreakTime,ArtNum,TNcash,TNcard,Amount
0,0,1,1.712071e+14,2017-12-07T14-23-23,2017-12-07T14:24:36,101,73,33,23,True,NoCard,112.71
1,1,1,1.712071e+14,2017-12-07T14-25-09,2017-12-07T14:27:00,101,111,28,29,True,NoCard,54.76
2,2,1,1.712071e+14,2017-12-07T14-27-28,2017-12-07T14:27:48,101,20,16,3,True,NoCard,14.77
3,3,1,1.712071e+14,2017-12-07T14-28-04,2017-12-07T14:28:29,101,25,71,12,True,NoCard,37.88
4,4,1,1.712071e+14,2017-12-07T14-29-40,2017-12-07T14:30:32,101,52,31,7,True,NoCard,115.34
...,...,...,...,...,...,...,...,...,...,...,...,...
126954,48551,1,1.904021e+11,2019-04-02T11-08-22,2019-04-02T11:09:14,603,52,16,8,True,NoCard,24.93
126955,48552,1,1.904021e+11,2019-04-02T11-09-30,2019-04-02T11:10:04,603,34,17,17,True,NoCard,51.71
126956,48553,1,1.904021e+11,2019-04-02T11-10-21,2019-04-02T11:11:03,603,42,10,19,True,NoCard,41.95
126957,48554,1,1.904021e+11,2019-04-02T11-11-13,2019-04-02T11:11:42,603,29,12,9,False,Card,47.96
126958,48555,1,1.904021e+11,2019-04-02T11-11-54,2019-04-02T11:12:16,603,22,7,6,True,NoCard,17.45

In [ ]:
tr1.to_csv('Cashh.csv', index=False)